version: "3.4"
services:
  game:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - ./:/app/
    ports:
      - 8080:8080
    command: go run blackgo/game/api
