version: "3.4"
services:
  db:
    image: postgres:14-alpine
    platform: linux/arm64/v8
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432

  broker:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  consumer:
    build:
      context: .
      dockerfile: Dockerfile
      target: consumer
    links:
      - db
      - broker
    env_file:
      - .env

  game:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    volumes:
      - ./:/app/
    ports:
      - 8080:8080
    links:
      - db
    env_file:
      - .env

  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - ./:/app/
    ports:
      - 8080:8080
    links:
      - db
    env_file:
      - .env
