name: Run tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.0

      - name: Run build
        run: go build blackgo/cli

      - name: Run tests
        run: |
          mkdir coverage/
          go test blackgo/deck -race -covermode=atomic -coverprofile=coverage/deck.out
          go test blackgo/engine -race -covermode=atomic -coverprofile=coverage/engine.out
          go test blackgo/utils -race -covermode=atomic -coverprofile=coverage/utils.out

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          verbose: true
